CleanArchit.Presantation.MVC/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CleanArchitHomework.Presentation.MVC.Controllers
{
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = roleManager.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View(new IdentityRole());
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            await roleManager.CreateAsync(role);
            return RedirectToAction("Index", "Home");
        }
    }
}

CleanArchit.Presantation.MVC/Controllers/UsersController.cs
using AutoMapper;
using CleanArchit.Presantation.MVC.Models;
using CleanArchit.Presantation.MVC.Models.AdminModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using Microsoft.AspNetCore.WebUtilities;

namespace CleanArchit.Presantation.MVC.Controllers
{
    public class UsersController : Controller
    {
        private UserManager<TeacherIdentity> _userManager;
        private IUserStore<TeacherIdentity> _userStore;
        private IUserEmailStore<TeacherIdentity> _emailStore;
        private IMapper _mapper;
        private RoleManager<IdentityRole> _roleManager;

        public UsersController(
            UserManager<TeacherIdentity> userManager,
            IUserStore<TeacherIdentity> userStore,
            IMapper mapper,
            RoleManager<IdentityRole> roleManager) 
        {
            _userManager = userManager;
            _userStore = userStore;
            _emailStore = GetEmailStore();
            _mapper = mapper;
            _roleManager = roleManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel userModel)
        {
            if(ModelState.IsValid)
            {
                TeacherIdentity teacher = new TeacherIdentity
                {
                    UserName = userModel.UserName,
                    Email = userModel.Email,
                    Name = userModel.Name,
                    DateOfBirth = userModel.DateOfBirth,
                    PhoneNumber = userModel.PhoneNumber,
                    SecondName = userModel.SecondName,
                    Sirname = userModel.Sirname,
                };
                var user = _mapper.Map<TeacherIdentity>(teacher);
                if(userModel.Role == "Admin")
                {
                    await _userManager.AddToRoleAsync(user, "Admin");
                } else
                {
                    await _userManager.AddToRoleAsync(user, "Teacher");
                }
                await _userStore.SetUserNameAsync(user, userModel.UserName, CancellationToken.None);
                await _emailStore.SetEmailAsync(user, userModel.Email, CancellationToken.None);
                var result = await _userManager.CreateAsync(user, userModel.Password);
                if(result.Succeeded)
                {
                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                    code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
                    await _userManager.ConfirmEmailAsync(user, code);
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(userModel);
        }

        public async Task<IActionResult> Edit(string id)
        {
            TeacherIdentity user = await _userManager.FindByIdAsync(id);
            if (user == null) 
            {
                return NotFound();
            }
            EditUserModel model = new EditUserModel
            {
                Id = user.Id,
                Email = user.Email,
                Name= user.Name,
                SecondName = user.SecondName,
                Sirname = user.Sirname,
                PhoneNumber = user.PhoneNumber,
                Role = await _userManager.IsInRoleAsync(user, "Admin")? "Admin" : "Teacher"
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit (EditUserModel model)
        {
            if(ModelState.IsValid)
            {
                TeacherIdentity teacher = await _userManager.FindByIdAsync(model.Id);
                if (teacher != null)
                {
                    teacher.Name = model.Name;
                    teacher.PhoneNumber = model.PhoneNumber;
                    teacher.Sirname = model.Sirname;
                    teacher.SecondName = model.SecondName;
                    teacher.Email = model.Email;
                    if(await _userManager.IsInRoleAsync(teacher, "Admin"))
                    {
                        await _userManager.RemoveFromRoleAsync(teacher, "Admin");
                    }
                    if (await _userManager.IsInRoleAsync(teacher, "Teacher"))
                    {
                        await _userManager.RemoveFromRoleAsync(teacher, "Teacher");
                    }
                    if(model.Role != null)
                    {
                        await _userManager.AddToRoleAsync(teacher, model.Role);
                    }

                    var result = await _userManager.UpdateAsync(teacher);
                    if(result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach(var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            TeacherIdentity user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
        private IUserEmailStore<TeacherIdentity> GetEmailStore()
        {
            if (!_userManager.SupportsUserEmail)
            {
                throw new NotSupportedException("The default UI requires a user store with email support.");
            }
            return (IUserEmailStore<TeacherIdentity>)_userStore;
        }
    }
}

CleanArchit.Presantation.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CleanArchit.Presantation.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CleanArchit.Presantation.MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StudentPage.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Auth.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Student Jurnal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="full">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top text-muted">
        <div class="container">
            &copy; 2023 - CleanArchit.Presantation.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>